DROP TABLE IF EXISTS Geo_sub_liquide;
DROP TABLE IF EXISTS Fournisseur_geo;
DROP TABLE IF EXISTS Fournisseur_liquide;
DROP TABLE IF EXISTS Client_liquide;
DROP TABLE IF EXISTS Client_geo;
DROP TABLE IF EXISTS Liquide_geo;
DROP TABLE IF EXISTS Geo_geo;

DROP TABLE IF EXISTS Etatique;
DROP TABLE IF EXISTS Regionale;
DROP TABLE IF EXISTS Metropolitaine;
DROP TABLE IF EXISTS Communale;

DROP TABLE IF EXISTS Pays;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS Metropole;
DROP TABLE IF EXISTS Commune;

DROP TABLE IF EXISTS Eau;
DROP TABLE IF EXISTS Jus;
DROP TABLE IF EXISTS Alcool;

DROP TABLE IF EXISTS Sub_valFix;
DROP TABLE IF EXISTS Sub_valHab;

DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Liquid;
DROP TABLE IF EXISTS Region_geo;
DROP TABLE IF EXISTS Fournisseur;
DROP TABLE IF EXISTS Subvention;

